Sprint 05
Filosuf/MovieQuiz-ios pull request #2
Opened 2022-08-25 08:07 UTC by Filosuf

2022-08-25 09:42 UTC, Filosuf commented
private var currentQuestion: QuizeQuestion! использован осознано. Странно работать контроллеру без вопроса. Пусть лучше упадет на этапе написания и тестирования. Если нужно, можно добавить в didReceiveNextQuestion жесткое переключение на ErrorAlert если не получили вопроса. В любом другом случаем при обращении к currentQuestion, переменная уже будет содержать вопрос.

2022-08-26 16:16 UTC, ABashkirova requested changes
Хорошая работа, есть места где нужно внимательно проверить себя

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    }
```suggestion
    private enum CodingKeys: String, CodingKey {
        case title = "fullTitle"
        case rating = "imDbRating"
        case imageURL = "image"
    }
```

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
```suggestion
    @IBOutlet private weak var activityIndicator: UIActivityIndicatorView!
```

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Navigation/AlertPresenter.swift
> +        guard let viewController = viewController else { return }
Во первых, этот код выглядит немножечко странно. Вы инициализируетесь с не опциональной ссылкой на viewController, но почему-то сохраняете ее в опциональную константу. При этом вы нигде эту ссылку не собираетесь обнулять (используется константа). И дальше, вы разыменовываете эту ссылку в каждой функции через guard. Выглядит как лишняя работа, можно же было сохранить и в не опциональную константу? И две строчки бы сэкономили! 

Тут хотелось бы, чтобы вы задавали себе вопросы: 
- `зачем опциональный тип?`, 
- `для чего он здесь служит?`, 
- `какой ситуации пытаемся избежать?`
- `когда ссылка может стать nil?` 

Во вторых, обратимся к месту вызова инициализатора – главный вью-контроллер: 

`private lazy var alertPresenter = AlertPresenter(viewController: self)`

Здесь уже проинициализованный viewController, создает ссылку на презентер и помещает в него ссылку на себя.

Теперь у вас есть `viewController` держащий ссылку на `alertPresenter`, и alertPresenter держащий ссылку на `viewController`.  
<img width="621" alt="Screenshot 2022-08-26 at 18 20 51" src="https://user-images.githubusercontent.com/20269264/186938628-1affceae-09eb-4b15-ab41-d6512a78370f.png">

Такая ситуация называется сильный цикл или цикл удержания (Retain Cycle). У нас есть специальный механизм автоматический счетчик ссылок([ARC](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html)), который позволяет считать ссылки на все объекты в программе и удалять их по мере неиспользования, чтобы очищать память. Очистка происходит когда ссылок на объект в памяти больше нет (счетчик равен нулю). Здесь при попытке деинициализировать вью-контроллер arc попытается очистить ссылку на презентер(уменьшить счетчик на 1), но не сможет из-за сильных связей друг на друга. Происходит утечка памяти.

Вам нужно обязательно разорвать сильную связь здесь, используя слабую ссылку на viewController. Ее можно разместить не приватным свойством и обойтись без инициализатора. 

Note: здесь это не страшно и не приводит к условному взрыву :) но в приложении с множеством экранов, повторная инициализация вьюконтроллера будет приводить к увеличению занимаемого пространства в оперативке. Не надо так! Приложение может начать подвисать или во все упасть по памяти!

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +//    ),
Вы можете убирать не используемый код :)  гит все помнит – если понадобится, вы знаете что это было где-то закомиченно и сможете восстановить этот фрагмент.

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
Аналогичная проблема: ссылка на делегат сильная. У вас в программе как минимум 2 сильных ссылки на контроллер из сущностей, которые создает и держит на них ссылки сам контроллер. Память не будет освобождена автоматически.

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/jsonContainer.swift
> +//    let actorList: [Actor]
Неиспользуемый код можно и нужно удалять)

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let questionsAmount = 3
Для отладки можно и 3, а для пользователя должно быть десять 😌 

Я тоже так делаю, и даже иногда забываю откатить настройки для тестов 🤫

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var currentQuestion: QuizeQuestion!
Я прочитала ваш комментарий к работе и в целом согласна: зачем работать с опциональным значением, если мы можем гарантировать, что оно всегда будет. 

Однако, давайте попробуем представить, что происходит, когда вы вызываете метод фабрики, загружающий следующий вопрос, а она возвращает вам через делегата опционал:
```
guard let question = question else { return }
currentQuestion = question
```

Вы выходите преждевременно из функции, не обновив состояние переменной `currentQuestion`. Приложение запросило новый вопрос, а он не вернулся, что осталось на экране? 

Предлагаю вам включить приложение, загрузить пару вопросов и выключить интернет  перед следующим ответом. Вы наверняка увидите постер с облачком. Но сможете ли вы дать верный ответ на вопрос? Будет ли это ответом на следующий вопрос или же на предыдущий? 

Очень надеюсь, что вы проанализируете эту ситуацию и найдете применение опциональному `currentQuestion: QuizeQuestion?` 🤗

2022-08-26 16:16 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Классно, что не забыли показать индикатор!  вы можете настроить скрытие activityIndicator один раз свойством `hidesWhenStopped` и использовать методы  startAnimating и stopAnimating

2022-08-27 19:24 UTC, ABashkirova commented on MovieQuiz/Navigation/AlertPresenter.swift
> +        guard let viewController = viewController else { return }
@Filosuf Евгений! Оказывается, в пятом спринте эту тему не рассматривали. Приношу извинения, что засчитала как ошибку. 

Надеюсь, вы ознакомились с темой и узнали что-то дополнительное и новое для себя! 
Тема очень важная, еще не раз встретитесь и ее всегда спрашивают на собеседованиях 👍

2022-08-28 13:42 UTC, Filosuf commented
activityIndicator. Я думал его нужно включать только на загрузку списка фильмов. Я делаю это только при при запуске приложения, может быть логично это сделать и на загрузку картинок, но в какой момент, так как у нас еще искусственная пауза в 1 секунду перед запросом? Индикатор на загрузку изображений добавил.

Сильные и слабые ссылки до конца не понял, поэтому отложил для будущих исправлений.

Что касается обработки ошибки загрузки данных (например отсутствие интернета). Согласно лекциям ошибки загрузки данных мы обрабатываем только при загрузке списка фильмов. Я загружаю список только при напуске приложения(точнее во ‘viewDidLoad()’, не вижу смысла этого делать при запуске каждого новой игры и в ТЗ не видел ограничений на этот счёт. Поэтому и ошибка не возникает только когда интернета нет при запуске приложения. 
Ошибку загрузки картинки мы никак не обрабатываем (кроме ‘print("Failed to load image»)’), поэтому и ErrorAlert не будет показан.

Что касается возможного прихода опционала для question: QuizeQuestion, то опционалом он может быть только за счёт протокола. В QuestionFactory методе requestNextQuestion мы кладем не опциональный тип. Ошибки по обработке не загруженных изображений, рейтингов и тд то это никак не обрабатывается. Прошу внимание обратить на материал лекции, например на ту же функцию ‘func requestNextQuestion()’. В ТЗ тоже не встречал требований доработать этот момент.

2022-09-01 17:22 UTC, Filosuf commented
Не понял по какой причине часто возникала ошибка обновления экрана не на основном потоке
пока не вынес еще раз на основной поток.  MovieQuizViewController.swift строка 224-226.       
DispatchQueue.main.async { [weak self] in
     self?.showNetworkError(message: "Данные повреждены или их не удалось загрузить")
 }
я не понимаю этой проблемы так как весь didReceiveNextQuestion вызывается только на основном потоке.
Что касаемо Вашего ревью, то мне оно очень нравится, всё подробно расписано, спасибо большое.

2022-09-01 17:27 UTC, Filosuf commented
Паузу в секунду оставил, так как при быстрой загрузке не успеваешь понять правильно ответил или нет

2022-09-02 11:29 UTC, merged